Repository colinaaa/algorithm-course-notes, pull requests merged in 2020-12, with the labels that each got.

#17 fix: make minor fixes on many chapters
  src/Ln11-LargeIntegerMultiplication.tex
  src/Network-flows.tex
  src/dynamic-programming-1.tex
  src/stable-matching.tex
Labels: enhancement

#23 Fix lecture 1 errors
  src/Ln1-AsymptoticOrderGrowth.tex
Labels: bug

#25 Finish Ln18-DP-ZeroOneKnapsack & Ln19-DP-ContextFreeGrammar
  Makefile
  book.tex
  src/Ln18-DP-ZeroOneKnapsack.tex
  src/Ln19-DP-ContextFreeGrammar.tex
Labels: new chapter

#28 fix a centering problem
  src/Image-segmentation.tex
Labels: bug, enhancement

#27 LN26:P and NP problem
  Makefile
  book.tex
  image/P_NP1.png
  image/P_NP2.png
  image/P_NP3.png
  image/P_NP4.png
  image/P_NP5.png
  src/Ln26-P-NP.tex
Labels: new chapter

#30 add network-flow-base.txt
  book.tex
  image/network-flow-backbone1.png
  image/network-flow-backbone2.png
  image/network-flow-backbone3.png
  image/network-flow-backbone4.png
  image/network-flow-backbone5.png
  image/network-flow-backbone6.png
  image/network-flow-ff-proof-graph1.png
  image/network-flow-ff-proof-graph2.png
  image/network-flow-greedy-example.png
  image/network-flow-greedy-example2.png
  image/network-flow-greedy-example3.png
  image/network-flow-residual-graph1.png
  src/network-flow-base.tex
Labels: new chapter

#29 finish ln06 ln07
  Makefile
  book.tex
  image/boruvka.png
  image/cutcutset.png
  image/cyclecutset.png
  image/exampleofMST.png
  image/exampleofST.png
  image/kruskal.png
  image/pathcycle.png
  image/prim.png
  image/redblue.png
  src/Image-segmentation.tex
  src/Ln06-MST.tex
  src/Ln07-redblue.tex
Labels: new chapter

#32 近似算法（Ln15，放在最后的章节）
  Makefile
  book.tex
  image/Ln15-ApproximationAlgorithm1.png
  image/example-problem-opt-solve.jpg
  image/greedy1-proof.jpg
  image/greedy1-result.jpg
  image/greedy2-proof-4-3.jpg
  image/greedy2-proof.jpg
  image/greedy2-result.jpg
  src/Ln15-ApproximationAlgorithm.tex
Labels: new chapter

#42 增加Ln17DP最短路径算法
  Makefile
  book.tex
  image/dijkstra1.png
  image/dijkstra2.png
  src/Ln17-DP-ShortestPath.tex
Labels: new chapter

#40 Ln16.字符串编辑距离
  Makefile
  book.tex
  image/connect1.png
  image/connect2.png
  src/LN16.tex
Labels: new chapter

#36 贪心算法 算法笔记提交
  Makefile
  book.tex
  src/Greedy-algorithm.tex
Labels: new chapter
